version: '3.3'

services:
  api_gateway:
    build: ./api_gateway
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - ./api_gateway/api_gateway/settings.py
    ports:
      - "8000:8000"

  auth_service:
    build: ./auth_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - ./auth_service/auth_service/settings.py
    restart: on-failure
    depends_on: 
      - auth_service_db

  exchange_service:
    build: ./exchange_service
    user: root
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - ./exchange_service/exchange_service/settings.py
    restart: on-failure
    depends_on: 
      - exchange_service_db

  task_handler_service:
    build: ./task_handler_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - ./task_handler_service/task_handler_service/settings.py
    restart: on-failure
    depends_on: 
      - task_handler_service_db

  predict_service:
    build: ./predict_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - ./predict_service/predict_service/settings.py
    restart: on-failure
    depends_on: 
      - predict_service_db

  auth_service_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${AUTH_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_DB_NAME}

  exchange_service_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${EXCHANGE_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${EXCHANGE_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${EXCHANGE_SERVICE_DB_NAME}

  task_handler_service_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TASK_HANDLER_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${TASK_HANDLER_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${TASK_HANDLER_SERVICE_DB_NAME}

  predict_service_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PREDICT_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${PREDICT_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${PREDICT_SERVICE_DB_NAME}

  celery:
    build: ./task_handler_service
    env_file:
      - .env
    command: celery -A task_handler_service worker --loglevel=INFO
    depends_on:
      - redis

  celery-beat:
    build: ./task_handler_service
    env_file:
      - .env
    command: celery -A task_handler_service beat --loglevel=INFO
    depends_on:
      - redis
  
  redis:
    image: redis

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - auth_service_db
      - exchange_service_db
    ports:
      - "8080:8080" 
