# Generated by Django 4.1.5 on 2023-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_email', models.CharField(max_length=64, unique=True)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
